spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      - id: mysise-demo1111
#        uri: lb://mysise-demo1  #目标地址
#        predicates:
#        - Path=/api/demo1/**  #路由规则
#        filters:
#        - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"
