spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/databasic?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      #初始化时建立物理连接的个数
      initial-size: 4
      # 最大连接池数量
      max-active: 8
      # 最小连接池数量
      min-idle: 5
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      test-on-borrow: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      pool-prepared-statements: true
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      min-evictable-idle-time-millis: 300000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      max-wait: 60000
      test-on-return: false
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:test
  aop:
    auto: true
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: org.mysise.basic.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
  config: classpath:log4j2.xml
feign:
  sentinel:
    enabled: true